src/SimpleDb.Web/Controllers/ClientsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SimpleDb.DataAccess;
using SimpleDb.DataAccess.Enities;
using SimpleDb.Models;

namespace SimpleDb.Controllers
{
  public class ClientsController : Controller
  {
    [HttpGet]
    public ActionResult Index()
    {
      List<Client> clients = null;
      List<ClientAddress> addresses = null;
      using (var ctx = new ResuestServiceContext())
      {
        clients = ctx.Clients.ToList();
        addresses = ctx.ClientAddresses.ToList();
      }

      var clientsWithAddresQuery = from c in clients
        join a in addresses on c.Symbol equals a.ClientSymbol
        select new ClientWithAddressModel
        {
          Symbol = c.Symbol,
          Name = c.Name,
          Email = c.Email,
          PhoneNumber = c.PhoneNumber,
          Description = c.Description,
          Street = a.Street,
          Number = a.Number,
          ZipCode = a.ZipCode,
          City = a.City
  };

      var clientsWithAddres = clientsWithAddresQuery.ToList();

      return View(clientsWithAddres);
    }
  }
}

src/SimpleDb.Web/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SimpleDb.DataAccess;
using SimpleDb.DataAccess.Enities;
using SimpleDb.Models;

namespace SimpleDb.Controllers
{
  public class RequestController : Controller
  {
    [HttpGet]
    public ActionResult Add(string clientSymbol)
    {
      var requestModel = new RequestAddModel
      {
        ClientSymbol = clientSymbol
      };

      return View(requestModel);
    }

    [HttpPost]
    public ActionResult Adding(RequestAddModel requestModel)
    {
      var request = new Request
      {
        Id = Guid.NewGuid(),
        ClientSymbol = requestModel.ClientSymbol,
        Description = requestModel.Description,
        RequestPriority = requestModel.RequestPriority,
        RequestType = requestModel.RequestType,
        RequestStatus = RequestStatus.Nowy,
        Date = DateTime.Now,
      };

      using (var ctx = new ResuestServiceContext())
      {
        ctx.Requests.Add(request);
        ctx.SaveChanges();
      }

      return RedirectToAction("Index", "Requests");
    }

    [HttpGet]
    public ActionResult Closing(Guid id)
    {
      using (var ctx = new ResuestServiceContext())
      {
        var request = ctx.Requests.SingleOrDefault(r => r.Id == id);
        request.RequestStatus = RequestStatus.Zamkniety;
        request.ResolveDate = DateTime.Now;
        ctx.SaveChanges();
      }

      return RedirectToAction("Index", "Requests");
    }

    [HttpGet]
    public ActionResult Assign(Guid id)
    {
      List<Employee> employees = null;
      using (var ctx = new ResuestServiceContext())
      {
        employees = ctx.Employees.ToList();
      }

      var requestEmployees = new RequestEmployeesModel
      {
        RequestId = id,
        Employees = employees.ToList().Select(e => new EmployeeModel
        {
          Identifier = e.Identifier,
          FirstName = e.FirstName,
          LastName = e.LastName
        }).ToList()
      };

      return View(requestEmployees);
    }

    [HttpPost]
    public ActionResult Assigning(RequestEmployeesModel requestEmployeesModel)
    {
      using (var ctx = new ResuestServiceContext())
      {
        var employeesToRemove = ctx.EmployeeRequests.Where(e => e.RequestId == requestEmployeesModel.RequestId).AsEnumerable();
        ctx.EmployeeRequests.RemoveRange(employeesToRemove);
        var employeeRequests = requestEmployeesModel.Employees.Where(e => e.IsAssigned).Select(e => new EmployeeRequest
        {
          RequestId = requestEmployeesModel.RequestId,
          EmployeeIdentifier = e.Identifier
        });
        ctx.EmployeeRequests.AddRange(employeeRequests);
        ctx.SaveChanges();
      }

      return RedirectToAction("Index", "Requests");
    }

    [HttpGet]
    public ActionResult Preview(Guid id)
    {
      RequestPreviewModel request = null;
      using (var ctx = new ResuestServiceContext())
      {
        request = ctx.Requests
          .Join(ctx.Clients, r => r.ClientSymbol, c => c.Symbol, (r, c) => new RequestPreviewModel
          {
            Id = r.Id,
            ClientSymbol = c.Symbol,
            RequestPriority = r.RequestPriority,
            RequestType = r.RequestType,
            Description = r.Description
          }).SingleOrDefault(r => r.Id == id);
        request.Employees = ctx.EmployeeRequests
          .Join(ctx.Employees, er => er.EmployeeIdentifier, r => r.Identifier, (er, r) => new
          {
            RequestId = er.RequestId,
            Identifier = r.Identifier,
            FirstName = r.FirstName,
            LastName = r.LastName
          }).Where(er => er.RequestId == id).Select(er => new EmployeeModel
          {
            Identifier = er.Identifier,
            FirstName = er.FirstName,
            LastName = er.LastName
          }).ToList();
      }

      return View(request);
    }
  }
}

src/SimpleDb.Web/Controllers/RequestsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SimpleDb.DataAccess;
using SimpleDb.Models;

namespace SimpleDb.Controllers
{
  public class RequestsController : Controller
  {
    [HttpGet]
    public ActionResult Index()
    {
      List<RequestForListModel> requests = null;
      using (var ctx = new ResuestServiceContext())
      {
        requests = ctx.Requests
          .Join(ctx.Clients, r => r.ClientSymbol, c => c.Symbol, (r, c) => new RequestForListModel
          {
            Identifier = r.Id,
            ClientName = c.Name,
            Date = r.Date,
            RequestPriority = r.RequestPriority,
            RequestType = r.RequestType,
            RequestStatus = r.RequestStatus,
            ResolveDate = r.ResolveDate
          }).ToList();
      }

      return View(requests);
    }
  }
}

src/SimpleDb.Web/Views/Request/Add.cshtml
@using SimpleDb.DataAccess.Enities
@model SimpleDb.Models.RequestAddModel

@{
  ViewBag.Title = "Dodaj zgłoszenie";
}

<h2>Dodaj zgłoszenie</h2>

@using (Html.BeginForm("Adding", "Request"))
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
      @Html.LabelFor(model => model.ClientSymbol, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.TextBoxFor(model => model.ClientSymbol, new { @class = "form-control", @readonly = "readonly" })
        @Html.ValidationMessageFor(model => model.ClientSymbol, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.RequestType, htmlAttributes: new {@class = "control-label col-md-2"})
      <div class="col-md-10">
        @Html.DropDownListFor(model => model.RequestType, EnumHelper.GetSelectList(typeof(RequestType)), new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.RequestType, "", new {@class = "text-danger"})
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.RequestPriority, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownListFor(model => model.RequestPriority, EnumHelper.GetSelectList(typeof(RequestPriority)), new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.RequestType, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control", rows = "6", cols = "10" })
        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Dodaj" class="btn btn-default" />
      </div>
    </div>
  </div>
}

<div>
  @Html.ActionLink("Wróć do listy", "Index", "Clients")
</div>

src/SimpleDb.Web/Views/Request/Assign.cshtml
@using System.Linq
@model SimpleDb.Models.RequestEmployeesModel

@{
  ViewBag.Title = "Przypisz pracowników";
}

<h2>Przypisz pracowników</h2>

@using (Html.BeginForm("Assigning", "Request"))
{
  @Html.AntiForgeryToken()
  <section id="data">
    @Html.HiddenFor(model => model.RequestId)
    <table class="table">
      <tr>
        <th>Imię</th>
        <th>Nazwisko</th>
        <th></th>
      </tr>
      @for (var i = 0; i < Model.Employees.Count(); i++)
      {
        @Html.HiddenFor(model => model.Employees[i].Identifier)
        <tr>
          <td>
            @Model.Employees[i].FirstName
          </td>
          <td>
            @Model.Employees[i].LastName
          </td>
          <td>
            @Html.CheckBoxFor(model => model.Employees[i].IsAssigned)
          </td>
        </tr>
      }
    </table>
    <p>
      <input type="submit" value="Zapisz" class="btn btn-default"/>
    </p>
  </section>
}

src/SimpleDb.Web/Views/Request/Preview.cshtml
@model SimpleDb.Models.RequestPreviewModel

@{
  ViewBag.Title = "Podgląd zgłoszenia";
}

<h2>Podgląd zgłoszenia</h2>

<div>
  <dl class="dl-horizontal">
    <dt>
      @Html.DisplayNameFor(model => model.ClientSymbol)
    </dt>

    <dd>
      @Html.DisplayFor(model => model.ClientSymbol)
    </dd>

    <dt>
      @Html.DisplayNameFor(model => model.RequestPriority)
    </dt>

    <dd>
      @Html.DisplayFor(model => model.RequestPriority)
    </dd>

    <dt>
      @Html.DisplayNameFor(model => model.RequestType)
    </dt>

    <dd>
      @Html.DisplayFor(model => model.RequestType)
    </dd>

    <dt>
      @Html.DisplayNameFor(model => model.Description)
    </dt>

    <dd>
      @Html.DisplayFor(model => model.Description)
    </dd>

  </dl>
</div>
<table class="table">
  <tr>
    <th>Identyfikator</th>
    <th>Imię</th>
    <th>Nazwisko</th>
  </tr>
  @foreach (var employee in Model.Employees)
      {
    <tr>
      <td>
        @employee.Identifier.ToString("N").ToUpper()
      </td>
      <td>
        @employee.FirstName
      </td>
      <td>
        @employee.LastName
      </td>
    </tr>
  }
</table>

<p>
  @Html.ActionLink("Wróć do listy", "Index", "Requests")
</p>