src/SimpleDb.Web/Controllers/ClientsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SimpleDb.DataAccess;
using SimpleDb.DataAccess.Enities;
using SimpleDb.Models;

namespace SimpleDb.Controllers
{
  public class ClientsController : Controller
  {
    [HttpGet]
    public ActionResult Index()
    {
      List<Client> clients = null;
      List<ClientAddress> addresses = null;
      using (var ctx = new ResuestServiceContext())
      {
        clients = ctx.Clients.ToList();
        addresses = ctx.ClientAddresses.ToList();
      }

      var clientsWithAddresQuery = from c in clients
        join a in addresses on c.Symbol equals a.ClientSymbol
        select new ClientWithAddressModel
        {
          Symbol = c.Symbol,
          Name = c.Name,
          Email = c.Email,
          PhoneNumber = c.PhoneNumber,
          Description = c.Description,
          Street = a.Street,
          Number = a.Number,
          ZipCode = a.ZipCode,
          City = a.City
  };

      var clientsWithAddres = clientsWithAddresQuery.ToList();

      return View(clientsWithAddres);
    }
  }
}

src/SimpleDb.Web/Controllers/EmployeesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SimpleDb.DataAccess;
using SimpleDb.Models;

namespace SimpleDb.Controllers
{
  public class EmployeesController : Controller
  {
    [HttpGet]
    public ActionResult Index()
    {
      List<EmployeeModel> employees = null;
      using (var ctx = new ResuestServiceContext())
      {
        employees = ctx.Employees.Select(x => new EmployeeModel
        {
          Identifier = x.Identifier,
          FirstName = x.FirstName,
          LastName = x.LastName
        }).ToList();
      }

      return View(employees);
    }
  }
}

src/SimpleDb.Web/Controllers/RequestsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SimpleDb.DataAccess;
using SimpleDb.Models;

namespace SimpleDb.Controllers
{
  public class RequestsController : Controller
  {
    [HttpGet]
    public ActionResult Index()
    {
      List<RequestForListModel> requests = null;
      using (var ctx = new ResuestServiceContext())
      {
        requests = ctx.Requests
          .Join(ctx.Clients, r => r.ClientSymbol, c => c.Symbol, (r, c) => new RequestForListModel
          {
            Identifier = r.Id,
            ClientName = c.Name,
            Date = r.Date,
            RequestPriority = r.RequestPriority,
            RequestType = r.RequestType,
            RequestStatus = r.RequestStatus,
            ResolveDate = r.ResolveDate
          }).ToList();
      }

      return View(requests);
    }
  }
}

src/SimpleDb.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title - My ASP.NET Application</title>
  <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
  <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
  <script src="~/Scripts/modernizr-2.6.2.js"></script>
  <meta name="description" content="Strona zgłoszeń do pomocy" />
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("Strona główna", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        @Html.ActionLink("Klienci", "Index", "Clients", new { area = "" }, new { @class = "navbar-brand" })
        @Html.ActionLink("Zgłoszenia", "Index", "Requests", new { area = "" }, new { @class = "navbar-brand" })
        @Html.ActionLink("Pracownicy", "Index", "Employees", new { area = "" }, new { @class = "navbar-brand" })
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav"></ul>
      </div>
    </div>
  </div>

  <div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
      <p>&copy; @DateTime.Now.Year - Jarosław Leszczyński</p>
    </footer>
  </div>

  <script src="~/Scripts/jquery-1.10.2.min.js"></script>
  <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>